name: sample-plan
on:
  push:
    branches-ignore:
      - '*-deploy'
jobs:
  sample-plan:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        environment: [dev]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
  
      - name: Authenticate to Google Cloud 
        uses: google-github-actions/auth@v1.0.0
        with:
          workload_identity_provider: ${{ secrets.WORKSHOP_GCP_WIPROVIDER }}
          service_account: ${{ secrets.WORKSHOP_GCP_SA }}
  
      - name: Setup-Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.3.7
          
      - run: terraform -chdir=terraform fmt -write=false -check=true
      - uses: actionshub/terraform-lint@main
      - run: terraform -chdir=terraform init -backend-config=bucket=kcj-kdap-asne1-dev-gcs-tfstate-001 -backend-config=prefix=kdap/${{ matrix.environment }}/workshop
      - run: terraform -chdir=terraform plan -var-file=_${{ matrix.environment }}.tfvars 